### ISSUE TITLE
Insert Dialogue functionality does not seem to be working

### ISSUE THREAD

**Issue by az4726** [morning4coffe-dev/storylines#1] opened 2021-09-01 22:09 UTC
![image](https://user-images.githubusercontent.com/35636613/131751640-bec2b094-97dd-4349-9d97-2c45adc5b075.png)
Hi there, as shown in the image, when I click 'Dialogue Mode', 'Add dialogue', or 'Add simple dialogue' a small card appears but nothing seems to happen when it is clicked on. Not sure what the expected result is, but I don't think this is it.

**Comment by morning4coffe-dev** [comment] 2021-09-02 15:42
Hello. Thank you so much for reporting this issue. 
You are right, this is not expected behavior. This issue is occurring because **you don't have any characters in your project**. 
To add a new character, go to View > Characters > Add > give it some name, and then Apply changes. After this go back to Insert and now you should see this character, and you should be able to add a new dialogue.

I will investigate this issue, the button should not be enabled, and it should give you some feedback that you don't have a character in your project. 
If you have more suggestions on this, please feel free to reply to this message. Or if you have any other suggestions or you found a different issue, feel free to create [New Issue](https://github.com/morning4coffe-dev/Storylines/issues/new).

**Comment by MidnightStuff** [comment] 2021-09-26 23:09
![image](https://user-images.githubusercontent.com/70477161/134827003-422940c6-9ef8-4dd1-8862-5b81cb4acfe1.png)
I have that same problem; no dialog about needing characters or anything pops up besides the blank, empty box that I circled that is missing content. I have no characters added; didn't know you could add characters. I just started using it like 5 minutes ago. 

My windows specs if it helps track it down:
![image](https://user-images.githubusercontent.com/70477161/134827272-c33f0641-da1d-42b0-b848-1437e01dc4de.png)

My .net version is  4.8.04084

Take Care, With Love Through God and Jesus and The Holy Ghost,

**Comment by morning4coffe-dev** [comment] 2021-09-27 21:03
> ![image](https://user-images.githubusercontent.com/70477161/134827003-422940c6-9ef8-4dd1-8862-5b81cb4acfe1.png)
> I have that same problem; no dialog about needing characters or anything pops up besides the blank, empty box that I circled that is missing content. I have no characters added; didn't know you could add characters. I just started using it like 5 minutes ago.
> 
> My windows specs if it helps track it down:
> ![image](https://user-images.githubusercontent.com/70477161/134827272-c33f0641-da1d-42b0-b848-1437e01dc4de.png)
> 
> My .net version is 4.8.04084
> 
> UPDATE:
> ![image](https://user-images.githubusercontent.com/70477161/134827426-16606bf5-a0d7-46bf-8959-6f46a1d99a23.png)
> When I click add dialog with a character, this comes up: Is that expected behavior? It seems more like code formatting.
> 
> The Simple Dialog works, though:
> ![image](https://user-images.githubusercontent.com/70477161/134827466-a5b0c61a-c4b1-4d32-8b74-72dd57147e91.png)
> 
> Take Care, With Love Through God and Jesus and The Holy Ghost,

Thank you for reminding me of this issue.
I have made some improvements to this, and the improvements are coming with a few others in the upcoming "pre-milestone" update 0.6.4 **hopefully tomorrow**. 
There is now a dialog with a message telling the user that there are no characters in the current project and there is a button to quickly add a new character. And in the Focus Mode dialog, there is an alert when you do not have any characters, telling you that you will not be able to add a new character until you leave (the Focus Mode).

And as for the code formatted dialogue, this is a completely expected behavior and those dialogues can be easily exported and have other benefits. But this feature will be simplified and improved in the future with a brand-new control from Community Toolkit. I am gonna open a new issue to track progress on this feature. 

If you have more suggestions on this, please feel free to reply to this message. If you have any other suggestions or you found a different issue, feel free to create [New Issue](https://github.com/morning4coffe-dev/storylines/issues/new).

**Comment by morning4coffe-dev** [comment] 2021-09-29 14:45
The new update with this and a few other issues fixed is now rolling out. Please check for updates on Microsoft Store. Thank you both @az4726 and @MidnightStuff very much for reporting this.
I am gonna close this issue but if you have any other suggestions or bugs, please feel free to open a [New issue](https://github.com/morning4coffe-dev/storylines/issues/new).

**Closed by morning4coffe-dev** 2021-09-29 14:45 UTC
Labels: bug
